import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, ManyToOne, JoinColumn, Index } from 'typeorm';
import { User } from '../../user/entities/user.entity';
import { ComplianceRuleEntity, RuleSeverity, ActionType } from './compliance-rule.entity';

export enum AlertStatus {
  OPEN = 'open',
  INVESTIGATING = 'investigating',
  RESOLVED = 'resolved',
  FALSE_POSITIVE = 'false_positive',
  ESCALATED = 'escalated',
}

export enum AlertPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

@Entity('compliance_alerts')
export class ComplianceAlertEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'alert_id' })
  @Column({ unique: true })
  alertId: string;

  @Column({ name: 'user_id' })
  @Index()
  userId: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column({ name: 'rule_id' })
  @Index()
  ruleId: string;

  @ManyToOne(() => ComplianceRuleEntity)
  @JoinColumn({ name: 'rule_id' })
  rule: ComplianceRuleEntity;

  @Column({ name: 'transaction_id', nullable: true })
  @Index()
  transactionId: string;

  @Column({ name: 'alert_type' })
  @Index()
  alertType: string;

  @Column({
    type: 'enum',
    enum: AlertStatus,
    default: AlertStatus.OPEN,
  })
  @Index()
  status: AlertStatus;

  @Column({
    type: 'enum',
    enum: AlertPriority,
  })
  @Index()
  priority: AlertPriority;

  @Column({
    type: 'enum',
    enum: RuleSeverity,
  })
  severity: RuleSeverity;

  @Column({ type: 'text' })
  title: string;

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'json' })
  triggerData: Record<string, any>;

  @Column({ type: 'json', nullable: true })
  contextData: Record<string, any>;

  @Column({
    type: 'enum',
    enum: ActionType,
  })
  actionTaken: ActionType;

  @Column({ type: 'json', nullable: true })
  actionResult: Record<string, any>;

  @Column({ name: 'risk_score', type: 'decimal', precision: 5, scale: 2 })
  riskScore: number;

  @Column({ name: 'confidence_score', type: 'decimal', precision: 5, scale: 2, nullable: true })
  confidenceScore: number;

  @Column({ name: 'is_false_positive', default: false })
  isFalsePositive: boolean;

  @Column({ name: 'investigation_notes', type: 'text', nullable: true })
  investigationNotes: string;

  @Column({ name: 'assigned_to', nullable: true })
  assignedTo: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'assigned_to' })
  assignee: User;

  @Column({ name: 'resolved_by', nullable: true })
  resolvedBy: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'resolved_by' })
  resolver: User;

  @Column({ name: 'resolution_details', type: 'text', nullable: true })
  resolutionDetails: string;

  @Column({ name: 'escalated_at', nullable: true })
  escalatedAt: Date;

  @Column({ name: 'resolved_at', nullable: true })
  resolvedAt: Date;

  @CreateDateColumn({ name: 'created_at' })
  @Index()
  createdAt: Date;

  @Column({ name: 'updated_at', nullable: true })
  updatedAt: Date;

  @Column({ name: 'external_reference', nullable: true })
  externalReference: string;

  @Column({ name: 'regulatory_report_required', default: false })
  regulatoryReportRequired: boolean;

  @Column({ name: 'regulatory_report_status', nullable: true })
  regulatoryReportStatus: string;

  @Column({ name: 'auto_generated', default: true })
  autoGenerated: boolean;
}
